GDBackend:
  default_quality: 100

Security:
  extensions:
    - SecurityExtension

SiteConfig:
  extensions:
    - BoilerplateConfig

Page:
  extensions:
    - PageExtension

ContentController:
  extensions:
    - PageControllerExtension

PaginatedList:
  extensions:
    - PaginatedListExtension

#LeftAndMain:
#  extra_requirements_css:
#    - Boilerplate/css/cms/css/cms.min.css