GDBackend:
  default_quality: 100

Security:
  extensions:
    - SecurityExtension

SiteConfig:
  extensions:
    - BoilerplateConfig

Page:
  extensions:
    - PageExtension

ContentController:
  extensions:
    - PageControllerExtension

#LeftAndMain:
#  extra_requirements_css:
#    - http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300
#    - boilerplate/css/cms/css/cms.min.css