GDBackend:
  default_quality: 100

SiteConfig:
  extensions:
    - BoilerplateConfig

ContentController:
  extensions:
    - PageExtension

PaginatedList:
  extensions:
    - PaginatedListExtension

SSViewer:
  theme: 'boilerplate'

#LeftAndMain:
#  extra_requirements_css:
#    - Boilerplate/css/cms/css/cms.min.css